fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    apt: "git://github.com/puppetlabs/puppetlabs-apt.git"
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
    python: "git://github.com/stankevich/puppet-python.git"
    nginx: "git://github.com/jfryman/puppet-nginx.git"
    apt: "git://github.com/puppetlabs/puppetlabs-apt.git"
  symlinks:
    docker_registry: "#{source_dir}"
